import { describe, expect, test } from 'bun:test';
import { mkdtemp, readFile, rm, stat, utimes } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { writeIfChanged } from './write-if-changed';

describe('writeIfChanged', () => {
    test('preserves content and modification time when generated bytes match', async () => {
        const directory = await mkdtemp(join(tmpdir(), 'ruimte-schema-'));
        const output = join(directory, 'contracts.json');
        try {
            expect(await writeIfChanged(output, 'one\n')).toBe(true);
            await utimes(output, new Date(1_000_000), new Date(1_000_000));
            const first = await stat(output, { bigint: true });

            expect(await writeIfChanged(output, 'one\n')).toBe(false);
            const second = await stat(output, { bigint: true });
            expect(second.mtimeNs).toBe(first.mtimeNs);
            expect(await readFile(output, 'utf8')).toBe('one\n');

            expect(await writeIfChanged(output, 'two\n')).toBe(true);
            expect(await readFile(output, 'utf8')).toBe('two\n');
        } finally {
            await rm(directory, { recursive: true, force: true });
        }
    });
});
