import { mkdir, readFile, realpath, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { DiagramDocument, DrawingDocument } from '@ruimte/contracts';
import { renderDiagram, renderDrawing } from '../../server/src/render/scenes.ts';

const root = resolve(import.meta.dir, '..');
const bundle = await Bun.build({
    entrypoints: [resolve(import.meta.dir, 'render-document.ts')],
    target: 'browser',
    format: 'iife',
    minify: true
});
if (!bundle.success) {
    throw new AggregateError(bundle.logs, 'Could not build the native document renderer');
}

const base = { x: 40, y: 60, w: 160, h: 80, stroke: 'blue' as const, strokeWidth: 2 as const, seed: 28 };
const drawing: DrawingDocument = {
    version: 1,
    rev: 9,
    elements: [
        { ...base, id: 'rect', kind: 'rect', radius: 8, roughness: 0 },
        { ...base, id: 'ellipse', kind: 'ellipse', fill: 'hachure', fillColor: 'green' },
        { ...base, id: 'diamond', kind: 'diamond', fill: 'solid', roughness: 2 },
        {
            ...base,
            id: 'line',
            kind: 'line',
            points: [
                [0, 0],
                [80, 40],
                [160, 0]
            ],
            arrowStart: true,
            arrowEnd: true,
            strokeStyle: 'dashed'
        },
        {
            ...base,
            id: 'pen',
            kind: 'freehand',
            points: [
                [0, 0, 0.2],
                [20, 15, 0.8],
                [50, 0, 0.5]
            ]
        },
        { ...base, id: 'text', kind: 'text', text: '<hello>\nworld', size: 24, font: 'mono', align: 'right' },
        { ...base, id: 'note', kind: 'note', text: 'A sticky note with several words', size: 20, fillColor: 'yellow', angle: Math.PI / 2, align: 'center' }
    ]
};
const diagram: DiagramDocument = {
    version: 1,
    rev: 4,
    meta: { title: 'Flow', direction: 'right' },
    nodes: [
        { id: 'a', label: 'Database', shape: 'cylinder', tone: 'blue', sub: 'Store' },
        { id: 'b', label: 'Client', shape: 'pill' }
    ],
    groups: [{ id: 'group', label: 'System', wraps: ['a', 'b'], tone: 'purple' }],
    edges: [{ from: 'a', to: 'b', label: 'Reads', style: 'dashed', tone: 'orange' }]
};
const fixtures = [
    { kind: 'drawing', document: drawing, scene: renderDrawing(drawing) },
    { kind: 'diagram', document: diagram, scene: renderDiagram(diagram) },
    { kind: 'drawing', document: { version: 1, rev: 0, elements: [] }, scene: renderDrawing({ version: 1, rev: 0, elements: [] }) }
];
const roughRoot = await realpath(resolve(root, '../../packages/drawing/node_modules/roughjs'));
const libraries = [
    ['roughjs', roughRoot],
    ['perfect-freehand', resolve(root, '../../packages/drawing/node_modules/perfect-freehand')],
    ...['hachure-fill', 'path-data-parser', 'points-on-curve', 'points-on-path'].map((name) => [name, resolve(roughRoot, '..', name)])
];
const licenses = await Promise.all(libraries.map(async ([name, path]) => `${name}\n\n${await readFile(resolve(path!, 'LICENSE'), 'utf8')}`));
const outputs = new Map([
    [
        'App/Resources/document-renderer.js',
        '// Generated by apps/ios/Scripts/generate-renderer.ts from the shared daemon scene renderer.\n' + (await bundle.outputs[0]!.text())
    ],
    ['Tests/Fixtures/document-scenes.json', JSON.stringify(fixtures) + '\n'],
    ['App/Resources/document-renderer-licenses.txt', licenses.join('\n\n')]
]);
for (const [path, contents] of outputs) {
    const destination = resolve(root, path);
    if (process.argv.includes('--check')) {
        if ((await readFile(destination, 'utf8').catch(() => '')) !== contents) {
            throw new Error(`Stale generated file: ${destination}`);
        }
    } else {
        await mkdir(resolve(destination, '..'), { recursive: true });
        await writeFile(destination, contents);
    }
}
console.log(`${process.argv.includes('--check') ? 'Checked' : 'Generated'} native document renderer and parity fixtures.`);
