import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { VISUAL_HOST_HEADERS } from '../../../packages/csp/src/index.ts';
import {
    VISUAL_BRIDGE_METHODS,
    VISUAL_LIMITS,
    VISUAL_THEME_VARIABLES,
    injectVisualBootstrap,
    visualFrameHeight,
    visualHostContextMessage,
    visualThemeFragment,
    type VisualTheme
} from '../../../packages/contracts/src/visual.ts';

const root = resolve(import.meta.dir, '..');

function swiftString(value: string): string {
    if ([...value].some((char) => char.charCodeAt(0) < 0x20)) {
        throw new Error(`A control character cannot go into a Swift literal: ${JSON.stringify(value)}`);
    }
    return `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`;
}

const fragmentKey = /^#([^=]+)=/.exec(visualThemeFragment({ appearance: 'light', variables: {} }))?.[1];
if (fragmentKey === undefined) {
    throw new Error('The theme fragment no longer starts with a key');
}

const headers = Object.entries(VISUAL_HOST_HEADERS)
    .map(([name, value]) => `        ${swiftString(name)}: ${swiftString(value)},`)
    .join('\n');
const variables = VISUAL_THEME_VARIABLES.map((name) => `        ${swiftString(name)},`).join('\n');

const contract = `// Generated by apps/ios/Scripts/generate-visual.ts from packages/csp and @adecore/agent-contracts/visual.
import Foundation

/// What a visual's page is served with and how it talks, as the desktop's host page of a visual has it.
enum ChatVisualContract {
    /// \`VISUAL_HOST_HEADERS\`, its \`Content-Security-Policy\` included.
    static let pageHeaders: [String: String] = [
${headers}
    ]
    /// \`VISUAL_THEME_VARIABLES\`, in their order.
    static let themeVariables: [String] = [
${variables}
    ]
    static let minHeight: Double = ${VISUAL_LIMITS.minHeight}
    static let maxHeight: Double = ${VISUAL_LIMITS.maxHeight}
    static let maxBytes = ${VISUAL_LIMITS.bytes}
    static let fragmentKey = ${swiftString(fragmentKey)}
    static let hostContextChanged = ${swiftString(VISUAL_BRIDGE_METHODS.hostContextChanged)}
}
`;

// Names and values a theme can carry, a quote, a space and a letter outside ASCII included.
const pairs: [string, string][] = [
    ['--background', '#131316'],
    ['--border', 'rgb(255 255 255 / 0.07)'],
    ['--radius', '12px'],
    ['--font-sans', '"Ünïcode Sans", -apple-system, sans-serif'],
    ['--chart-1', '#ffffff']
];
const theme: VisualTheme = { appearance: 'dark', variables: Object.fromEntries(pairs) };
const measured = {
    maxHeight: 2000,
    heights: [
        [320, 500.2],
        [480, 800],
        [800, 300]
    ] as [number, number][]
};
const heightCases = [
    ...[200, 320, 400, 480, 600, 800, 1000].map((width) => ({ visual: measured, width })),
    { visual: { ...measured, maxHeight: 400 }, width: 400 },
    { visual: { maxHeight: 2000, heights: [[360, 10]] as [number, number][] }, width: 360 },
    { visual: { maxHeight: 2000, heights: [[360, 3000]] as [number, number][] }, width: 360 },
    { visual: { maxHeight: 2000 }, width: 360 }
].map((sample) => ({ ...sample, height: visualFrameHeight(sample.visual, sample.width) ?? null }));

// A page as the machine stores it, the bootstrap in front, which a test draws in the app's own web view.
const page = injectVisualBootstrap(
    '<!doctype html><html><head><title>Chart</title></head><body><div style="height: 320px; background: var(--chart-1)"></div></body></html>'
);

const fixtures = {
    page,
    theme: { appearance: theme.appearance, variables: pairs },
    fragment: visualThemeFragment(theme),
    hostContext: visualHostContextMessage(theme),
    heights: heightCases
};

const outputs = new Map([
    ['App/Sessions/ChatVisualContract.swift', contract],
    ['Tests/Fixtures/visuals.json', JSON.stringify(fixtures, null, 2) + '\n']
]);
for (const [path, contents] of outputs) {
    const destination = resolve(root, path);
    if (process.argv.includes('--check')) {
        if ((await readFile(destination, 'utf8').catch(() => '')) !== contents) {
            throw new Error(`Stale generated file: ${destination}`);
        }
    } else {
        await mkdir(resolve(destination, '..'), { recursive: true });
        await writeFile(destination, contents);
    }
}
console.log(`${process.argv.includes('--check') ? 'Checked' : 'Generated'} the visual contract and its parity fixtures.`);
