import {
    Beaker,
    Book,
    Bookmark,
    Bot,
    Box,
    Boxes,
    Brain,
    Brush,
    Camera,
    Cloud,
    Code,
    Coffee,
    Compass,
    Cpu,
    Database,
    FileText,
    Flag,
    Flame,
    Folder,
    Gamepad2,
    Globe,
    Hammer,
    Heart,
    Key,
    Layers,
    Leaf,
    Map,
    Music,
    Package,
    Palette,
    Puzzle,
    Rocket,
    Server,
    Shield,
    Sparkles,
    Star,
    Terminal,
    Video,
    Wrench,
    Zap,
    type LucideIcon
} from 'lucide-react';
import { PROJECT_ICON_NAMES } from '@ruimte/contracts';

/* The closed list from the contracts, drawn. A name outside it never reaches the client. */
export const PROJECT_ICON_GLYPHS: Record<(typeof PROJECT_ICON_NAMES)[number], LucideIcon> = {
    box: Box,
    boxes: Boxes,
    package: Package,
    layers: Layers,
    code: Code,
    terminal: Terminal,
    cpu: Cpu,
    database: Database,
    server: Server,
    cloud: Cloud,
    globe: Globe,
    rocket: Rocket,
    zap: Zap,
    flame: Flame,
    sparkles: Sparkles,
    star: Star,
    heart: Heart,
    flag: Flag,
    bookmark: Bookmark,
    folder: Folder,
    'file-text': FileText,
    book: Book,
    puzzle: Puzzle,
    palette: Palette,
    brush: Brush,
    camera: Camera,
    music: Music,
    video: Video,
    'gamepad-2': Gamepad2,
    bot: Bot,
    brain: Brain,
    beaker: Beaker,
    wrench: Wrench,
    hammer: Hammer,
    shield: Shield,
    key: Key,
    compass: Compass,
    map: Map,
    leaf: Leaf,
    coffee: Coffee
};
