import {
    Activity,
    Anchor,
    AppWindow,
    Archive,
    Atom,
    AudioWaveform,
    Battery,
    Beaker,
    Bell,
    Bike,
    Binary,
    Blocks,
    Bluetooth,
    Book,
    Bookmark,
    Bot,
    BotMessageSquare,
    Box,
    Boxes,
    Braces,
    Brain,
    BrainCircuit,
    Briefcase,
    Brush,
    Bug,
    Cable,
    Calculator,
    Calendar,
    Camera,
    ChartColumn,
    ChartLine,
    ChartPie,
    CircuitBoard,
    Clapperboard,
    ClipboardList,
    Cloud,
    CloudCog,
    Code,
    CodeXml,
    Coffee,
    Compass,
    Component,
    Container,
    Cpu,
    Database,
    Dna,
    Dumbbell,
    EthernetPort,
    FileCode,
    FileText,
    Film,
    FingerprintPattern,
    Flag,
    Flame,
    FlaskConical,
    Folder,
    Frame,
    Gamepad2,
    Gauge,
    Gift,
    GitBranch,
    GitFork,
    GitMerge,
    GitPullRequest,
    Globe,
    GraduationCap,
    Hammer,
    Handshake,
    HardDrive,
    Headphones,
    Heart,
    Hourglass,
    House,
    Image,
    Inbox,
    Key,
    Keyboard,
    Languages,
    Laptop,
    Layers,
    LayoutDashboard,
    LayoutTemplate,
    Leaf,
    LibraryBig,
    LifeBuoy,
    Lightbulb,
    ListTodo,
    Lock,
    Mail,
    Map,
    Megaphone,
    MemoryStick,
    MessagesSquare,
    Mic,
    Microchip,
    Milestone,
    Monitor,
    Moon,
    Mountain,
    Mouse,
    MousePointerClick,
    Music,
    Network,
    Newspaper,
    Notebook,
    NotebookPen,
    Orbit,
    Package,
    Palette,
    PanelsTopLeft,
    PawPrint,
    PcCase,
    PencilRuler,
    PenTool,
    Pin,
    Pizza,
    Plane,
    Plug,
    Presentation,
    Printer,
    Puzzle,
    Quote,
    RadioTower,
    Regex,
    Rocket,
    Router,
    SatelliteDish,
    ScanEye,
    ScrollText,
    Server,
    ServerCog,
    Shapes,
    Sheet,
    Shield,
    Ship,
    ShoppingCart,
    Sigma,
    Smartphone,
    Sparkles,
    Sprout,
    SquareKanban,
    SquareTerminal,
    Star,
    Store,
    Sun,
    SwatchBook,
    Table,
    Tablet,
    Target,
    Telescope,
    Terminal,
    TestTubeDiagonal,
    Thermometer,
    Timer,
    Trees,
    Trophy,
    Type,
    Usb,
    Users,
    Variable,
    Video,
    Wallet,
    WandSparkles,
    Watch,
    Webcam,
    Webhook,
    Wifi,
    Workflow,
    Wrench,
    Zap,
    type LucideIcon
} from 'lucide-react';
import { isProjectIconName, type ProjectIconName } from '@ruimte/contracts';

export type ProjectIconGroupId = 'general' | 'code' | 'ai' | 'web' | 'infra' | 'data' | 'hardware' | 'design' | 'writing' | 'planning' | 'life';

export interface ProjectIconGroup {
    readonly id: ProjectIconGroupId;
    readonly icons: Partial<Record<ProjectIconName, LucideIcon>>;
}

/* The closed list from the contracts, drawn in the order a person browses it. Its label is `common:icon.group.<id>`. */
export const PROJECT_ICON_GROUPS: readonly ProjectIconGroup[] = [
    {
        id: 'general',
        icons: {
            folder: Folder,
            box: Box,
            boxes: Boxes,
            package: Package,
            layers: Layers,
            puzzle: Puzzle,
            star: Star,
            heart: Heart,
            flag: Flag,
            bookmark: Bookmark,
            pin: Pin,
            target: Target,
            lightbulb: Lightbulb,
            archive: Archive,
            inbox: Inbox,
            house: House,
            briefcase: Briefcase,
            sparkles: Sparkles,
            zap: Zap,
            flame: Flame,
            rocket: Rocket
        }
    },
    {
        id: 'code',
        icons: {
            code: Code,
            'code-xml': CodeXml,
            braces: Braces,
            terminal: Terminal,
            'square-terminal': SquareTerminal,
            'file-code': FileCode,
            binary: Binary,
            regex: Regex,
            variable: Variable,
            blocks: Blocks,
            component: Component,
            'git-branch': GitBranch,
            'git-merge': GitMerge,
            'git-pull-request': GitPullRequest,
            'git-fork': GitFork,
            bug: Bug,
            'test-tube-diagonal': TestTubeDiagonal,
            'flask-conical': FlaskConical,
            beaker: Beaker,
            wrench: Wrench,
            hammer: Hammer,
            workflow: Workflow,
            webhook: Webhook
        }
    },
    {
        id: 'ai',
        icons: {
            bot: Bot,
            'bot-message-square': BotMessageSquare,
            brain: Brain,
            'brain-circuit': BrainCircuit,
            'wand-sparkles': WandSparkles,
            'messages-square': MessagesSquare,
            'scan-eye': ScanEye,
            'audio-waveform': AudioWaveform
        }
    },
    {
        id: 'web',
        icons: {
            globe: Globe,
            'app-window': AppWindow,
            'layout-dashboard': LayoutDashboard,
            'layout-template': LayoutTemplate,
            'panels-top-left': PanelsTopLeft,
            'mouse-pointer-click': MousePointerClick,
            smartphone: Smartphone,
            tablet: Tablet,
            'shopping-cart': ShoppingCart,
            store: Store,
            mail: Mail
        }
    },
    {
        id: 'infra',
        icons: {
            server: Server,
            'server-cog': ServerCog,
            database: Database,
            container: Container,
            cloud: Cloud,
            'cloud-cog': CloudCog,
            network: Network,
            router: Router,
            gauge: Gauge,
            activity: Activity,
            'scroll-text': ScrollText,
            bell: Bell,
            shield: Shield,
            lock: Lock,
            key: Key,
            'fingerprint-pattern': FingerprintPattern
        }
    },
    {
        id: 'data',
        icons: {
            'chart-line': ChartLine,
            'chart-column': ChartColumn,
            'chart-pie': ChartPie,
            table: Table,
            sheet: Sheet,
            calculator: Calculator,
            sigma: Sigma,
            atom: Atom,
            dna: Dna,
            telescope: Telescope,
            orbit: Orbit
        }
    },
    {
        id: 'hardware',
        icons: {
            cpu: Cpu,
            microchip: Microchip,
            'circuit-board': CircuitBoard,
            'memory-stick': MemoryStick,
            'pc-case': PcCase,
            laptop: Laptop,
            monitor: Monitor,
            keyboard: Keyboard,
            mouse: Mouse,
            webcam: Webcam,
            printer: Printer,
            'hard-drive': HardDrive,
            usb: Usb,
            headphones: Headphones,
            watch: Watch,
            battery: Battery,
            bluetooth: Bluetooth,
            thermometer: Thermometer,
            'ethernet-port': EthernetPort,
            cable: Cable,
            plug: Plug,
            wifi: Wifi,
            'radio-tower': RadioTower,
            'satellite-dish': SatelliteDish
        }
    },
    {
        id: 'design',
        icons: {
            palette: Palette,
            brush: Brush,
            'pen-tool': PenTool,
            'pencil-ruler': PencilRuler,
            shapes: Shapes,
            frame: Frame,
            'swatch-book': SwatchBook,
            type: Type,
            image: Image,
            camera: Camera,
            film: Film,
            clapperboard: Clapperboard,
            video: Video,
            music: Music,
            mic: Mic,
            'gamepad-2': Gamepad2
        }
    },
    {
        id: 'writing',
        icons: {
            'file-text': FileText,
            book: Book,
            notebook: Notebook,
            'notebook-pen': NotebookPen,
            'library-big': LibraryBig,
            newspaper: Newspaper,
            'graduation-cap': GraduationCap,
            languages: Languages,
            quote: Quote,
            presentation: Presentation,
            megaphone: Megaphone
        }
    },
    {
        id: 'planning',
        icons: {
            'list-todo': ListTodo,
            'square-kanban': SquareKanban,
            'clipboard-list': ClipboardList,
            calendar: Calendar,
            milestone: Milestone,
            trophy: Trophy,
            hourglass: Hourglass,
            timer: Timer,
            users: Users,
            handshake: Handshake,
            wallet: Wallet,
            compass: Compass,
            map: Map
        }
    },
    {
        id: 'life',
        icons: {
            leaf: Leaf,
            sprout: Sprout,
            trees: Trees,
            mountain: Mountain,
            sun: Sun,
            moon: Moon,
            plane: Plane,
            ship: Ship,
            anchor: Anchor,
            'life-buoy': LifeBuoy,
            coffee: Coffee,
            pizza: Pizza,
            gift: Gift,
            dumbbell: Dumbbell,
            bike: Bike,
            'paw-print': PawPrint
        }
    }
];

export const PROJECT_ICON_GLYPHS = Object.fromEntries(PROJECT_ICON_GROUPS.flatMap((group) => Object.entries(group.icons))) as Record<
    ProjectIconName,
    LucideIcon
>;

/* The glyph of a picked name, or null for one a newer Ruimte offers that this version cannot draw. */
export const projectIconGlyphOf = (name: string): LucideIcon | null => (isProjectIconName(name) ? PROJECT_ICON_GLYPHS[name] : null);

// The words a search finds an icon by beyond its own name.
export const PROJECT_ICON_KEYWORDS: Partial<Record<ProjectIconName, readonly string[]>> = {
    house: ['home', 'smart home'],
    'git-branch': ['version'],
    'git-pull-request': ['pr', 'review'],
    bug: ['debug', 'issue'],
    'test-tube-diagonal': ['test'],
    'flask-conical': ['test', 'experiment'],
    workflow: ['pipeline', 'ci'],
    webhook: ['api'],
    bot: ['agent', 'ai', 'claude', 'codex'],
    'bot-message-square': ['chat', 'agent'],
    brain: ['ai', 'model'],
    'wand-sparkles': ['magic', 'generate'],
    'messages-square': ['chat'],
    'audio-waveform': ['voice', 'speech'],
    'app-window': ['desktop', 'electron'],
    'layout-dashboard': ['admin'],
    'panels-top-left': ['website'],
    smartphone: ['ios', 'mobile'],
    'shopping-cart': ['shop', 'ecommerce'],
    store: ['shop'],
    mail: ['email', 'newsletter'],
    container: ['docker', 'kubernetes'],
    gauge: ['performance'],
    activity: ['monitoring'],
    'scroll-text': ['logs'],
    'fingerprint-pattern': ['auth', 'identity'],
    sheet: ['spreadsheet'],
    dna: ['bio'],
    microchip: ['embedded', 'firmware'],
    thermometer: ['sensor'],
    'pen-tool': ['vector'],
    image: ['photo'],
    'gamepad-2': ['game'],
    'library-big': ['docs', 'documentation'],
    'graduation-cap': ['course', 'school'],
    languages: ['i18n', 'translation'],
    presentation: ['slides'],
    'list-todo': ['tasks', 'checklist'],
    'square-kanban': ['board'],
    users: ['team'],
    wallet: ['finance', 'money']
};
