import {
    Beaker,
    Book,
    Bookmark,
    Bot,
    Box,
    Boxes,
    Brain,
    Brush,
    Cable,
    Camera,
    CircuitBoard,
    Cloud,
    Code,
    Coffee,
    Compass,
    Container,
    Cpu,
    Database,
    EthernetPort,
    FileText,
    Flag,
    Flame,
    Folder,
    Gamepad2,
    Globe,
    Hammer,
    HardDrive,
    Heart,
    Key,
    Laptop,
    Layers,
    Leaf,
    Map,
    MemoryStick,
    Monitor,
    Music,
    Network,
    Package,
    Palette,
    PcCase,
    Plug,
    Printer,
    Puzzle,
    RadioTower,
    Rocket,
    Router,
    SatelliteDish,
    Server,
    Shield,
    Smartphone,
    Sparkles,
    Star,
    Tablet,
    Terminal,
    Usb,
    Video,
    Webcam,
    Wifi,
    Wrench,
    Zap,
    type LucideIcon
} from 'lucide-react';
import { PROJECT_ICON_NAMES } from '@ruimte/contracts';

/* The closed list from the contracts, drawn. A name outside it never reaches the client. */
export const PROJECT_ICON_GLYPHS: Record<(typeof PROJECT_ICON_NAMES)[number], LucideIcon> = {
    box: Box,
    boxes: Boxes,
    package: Package,
    layers: Layers,
    code: Code,
    terminal: Terminal,
    cpu: Cpu,
    'circuit-board': CircuitBoard,
    'memory-stick': MemoryStick,
    'pc-case': PcCase,
    laptop: Laptop,
    monitor: Monitor,
    smartphone: Smartphone,
    tablet: Tablet,
    webcam: Webcam,
    printer: Printer,
    'hard-drive': HardDrive,
    usb: Usb,
    database: Database,
    server: Server,
    container: Container,
    network: Network,
    router: Router,
    'ethernet-port': EthernetPort,
    cable: Cable,
    plug: Plug,
    wifi: Wifi,
    'radio-tower': RadioTower,
    'satellite-dish': SatelliteDish,
    cloud: Cloud,
    globe: Globe,
    rocket: Rocket,
    zap: Zap,
    flame: Flame,
    sparkles: Sparkles,
    star: Star,
    heart: Heart,
    flag: Flag,
    bookmark: Bookmark,
    folder: Folder,
    'file-text': FileText,
    book: Book,
    puzzle: Puzzle,
    palette: Palette,
    brush: Brush,
    camera: Camera,
    music: Music,
    video: Video,
    'gamepad-2': Gamepad2,
    bot: Bot,
    brain: Brain,
    beaker: Beaker,
    wrench: Wrench,
    hammer: Hammer,
    shield: Shield,
    key: Key,
    compass: Compass,
    map: Map,
    leaf: Leaf,
    coffee: Coffee
};
