// Generated by apps/ios/Scripts/generate-visual.ts from packages/csp and @adecore/agent-contracts/visual.
import Foundation

/// What a visual's page is served with and how it talks, as the desktop's host page of a visual has it.
enum ChatVisualContract {
    /// `VISUAL_HOST_HEADERS`, its `Content-Security-Policy` included.
    static let pageHeaders: [String: String] = [
        "content-type": "text/html; charset=utf-8",
        "content-security-policy": "default-src 'none'; script-src 'unsafe-inline' 'unsafe-eval' https: data: blob:; style-src 'unsafe-inline' https: data:; img-src https: data: blob:; font-src https: data:; media-src https: data: blob:; connect-src https: wss: data: blob:; worker-src blob: data:; frame-src https: data: blob:; form-action 'none'; base-uri 'none'; frame-ancestors 'self'; sandbox allow-scripts allow-forms",
        "x-content-type-options": "nosniff",
        "referrer-policy": "no-referrer",
        "cache-control": "no-cache",
    ]
    /// `VISUAL_THEME_VARIABLES`, in their order.
    static let themeVariables: [String] = [
        "--background",
        "--foreground",
        "--muted",
        "--muted-foreground",
        "--card",
        "--card-foreground",
        "--popover",
        "--popover-foreground",
        "--secondary",
        "--secondary-foreground",
        "--border",
        "--input",
        "--ring",
        "--primary",
        "--primary-foreground",
        "--accent",
        "--accent-foreground",
        "--destructive",
        "--destructive-foreground",
        "--warning",
        "--warning-foreground",
        "--success",
        "--success-foreground",
        "--info",
        "--info-foreground",
        "--code-background",
        "--code-foreground",
        "--chart-1",
        "--chart-2",
        "--chart-3",
        "--chart-4",
        "--chart-5",
        "--chart-6",
        "--radius",
        "--font-sans",
        "--font-mono",
    ]
    static let minHeight: Double = 80
    static let maxHeight: Double = 2000
    static let maxBytes = 16777216
    static let fragmentKey = "visual-theme"
    static let hostContextChanged = "ui/notifications/host-context-changed"
}
