import type { AgentKind } from '@ruimte/contracts';
import {
    Activity,
    AppWindow,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ChartSpline,
    Braces,
    ChevronsLeft,
    ChevronsRight,
    CircleHelp,
    Command,
    Compass,
    Copy,
    CornerUpRight,
    Download,
    Eraser,
    Eye,
    File,
    FileText,
    Focus,
    Folder,
    FolderCog,
    FolderOpen,
    Frame,
    Fullscreen,
    Gauge,
    GitBranch,
    GitFork,
    Globe,
    Group,
    Heading,
    Inbox,
    Info,
    Keyboard,
    Layers,
    LayoutDashboard,
    Lock,
    Maximize2,
    MessageSquare,
    Minus,
    PanelBottom,
    PanelLeft,
    PanelRight,
    PanelRightOpen,
    Pencil,
    PenTool,
    Percent,
    Plus,
    Redo2,
    Save,
    ScrollText,
    Search,
    Server,
    Settings,
    Settings2,
    SquareArrowOutUpRight,
    SquareDashed,
    StickyNote,
    SunMoon,
    TabletSmartphone,
    Terminal,
    TextSearch,
    Trash,
    Type,
    Undo2,
    Users,
    Workflow,
    X,
    Bot,
    type LucideIcon
} from 'lucide-react';

/* What the web client draws in front of a row, so every label starts on the same line. The shell's native menu has none. */
export type MenuIcon = { icon: LucideIcon } | { agent: AgentKind };

const ICONS: Partial<Record<string, LucideIcon>> = {
    file: File,
    edit: Pencil,
    view: Eye,
    go: Compass,
    window: AppWindow,
    help: CircleHelp,
    'kind-canvas': Frame,
    'kind-drawing': PenTool,
    'kind-diagram': Workflow,
    'kind-chat': MessageSquare,
    'kind-terminal': Terminal,
    'kind-browser': Globe,
    'kind-file': FileText,
    'new-view': Plus,
    'new-agent': Bot,
    'move-to': CornerUpRight,
    layouts: LayoutDashboard,
    'delete-layout': Trash,
    about: Info,
    settings: Settings,
    'project-settings': FolderCog,
    'open-folder': FolderOpen,
    reveal: CornerUpRight,
    'close-cell': X,
    'view-new': Frame,
    'view-new-drawing': PenTool,
    'view-new-diagram': Workflow,
    'view-new-terminal': Terminal,
    'view-new-file': FileText,
    'view-new-browser': Globe,
    'view-new-separator': Minus,
    'view-new-subheader': Heading,
    'edit-undo': Undo2,
    'edit-redo': Redo2,
    find: TextSearch,
    'find-in-files': Search,
    sidebar: PanelLeft,
    'panel-files': Folder,
    'panel-git': GitBranch,
    'panel-devices': TabletSmartphone,
    'panel-toggle': PanelRightOpen,
    'split-right': PanelRight,
    'split-down': PanelBottom,
    fit: Maximize2,
    'zoom-selection': Focus,
    'zoom-reset': Percent,
    theme: SunMoon,
    fullscreen: Fullscreen,
    'add-terminal': Terminal,
    'add-chat': MessageSquare,
    'add-browser': Globe,
    'add-note': StickyNote,
    'add-text': Type,
    'add-file': FileText,
    'add-group': Group,
    'group-selection': SquareDashed,
    'view-promote': SquareArrowOutUpRight,
    lock: Lock,
    'layout-save': Save,
    'terminal-clear': Eraser,
    'view-fork': GitFork,
    'view-open-in-chat': MessageSquare,
    'view-open-in-terminal': Terminal,
    'view-duplicate': Copy,
    'view-put-on-canvas': Frame,
    'view-reveal': CornerUpRight,
    'view-share': Users,
    'view-settings': Settings2,
    'view-delete': Trash,
    'diagram-open-json': Braces,
    palette: Command,
    'view-previous': ChevronsLeft,
    'view-next': ChevronsRight,
    'focus-left': ArrowLeft,
    'focus-right': ArrowRight,
    'focus-up': ArrowUp,
    'focus-down': ArrowDown,
    prompts: Inbox,
    'panel-processes': Activity,
    usage: Gauge,
    models: ChartSpline,
    'settings-machines': Server,
    'release-notes': ScrollText,
    'settings-keyboard': Keyboard
};

/* Rows that exist once per agent, layout, view or format, by the start of their id. */
const PREFIXES: [prefix: string, icon: LucideIcon][] = [
    ['layout-apply-', LayoutDashboard],
    ['layout-delete-', Trash],
    ['view-move-', ArrowRight],
    ['go-view-', Layers],
    ['diagram-copy-', Copy],
    ['drawing-copy-', Copy],
    ['diagram-save-', Download],
    ['drawing-save-', Download],
    ['diagram-show-', Frame],
    ['drawing-show-', Frame]
];

const AGENT_ROW = /^agent-(?:view-)?(?:chat|terminal)-(.+)$/;

export const menuIconOf = (id: string): MenuIcon | null => {
    const agent = AGENT_ROW.exec(id)?.[1];
    if (agent !== undefined) {
        return { agent: agent as AgentKind };
    }
    const icon = ICONS[id] ?? PREFIXES.find(([prefix]) => id.startsWith(prefix))?.[1];
    return icon === undefined ? null : { icon };
};
