import type { AgentKind } from '@ruimte/contracts';
import {
    Activity,
    ArrowDownToLine,
    ArrowUpToLine,
    Columns3,
    BoxSelect,
    ScanSearch,
    TextCursor,
    ChevronsDownUp,
    ChevronsUpDown,
    FoldHorizontal,
    FoldVertical,
    ListCollapse,
    ListTree,
    UnfoldVertical,
    IndentIncrease,
    CaseSensitive,
    CornerLeftUp,
    CornerDownLeft,
    Split,
    Merge,
    Code,
    Slash,
    AlignLeft,
    AppWindow,
    AtSign,
    ArrowDown,
    ArrowLeft,
    ArrowRight,
    ArrowRightToLine,
    ArrowUp,
    ChartSpline,
    Braces,
    ChevronsLeft,
    ChevronsRight,
    CircleAlert,
    CircleHelp,
    CircleStop,
    CodeXml,
    Command,
    Compass,
    Copy,
    CornerUpRight,
    Download,
    Eraser,
    Expand,
    Eye,
    File,
    FilePlus,
    FileText,
    Flag,
    Focus,
    Folder,
    FolderCog,
    FolderOpen,
    FolderPlus,
    Frame,
    Fullscreen,
    Gauge,
    GitBranch,
    GitFork,
    Globe,
    Group,
    Heading,
    Blocks,
    Lightbulb,
    LocateFixed,
    MapPin,
    ListOrdered,
    Inbox,
    History,
    Info,
    Parentheses,
    FileSearch,
    Keyboard,
    Layers,
    ListChecks,
    ListX,
    LayoutDashboard,
    Lock,
    Maximize2,
    MessageSquare,
    MessageSquarePlus,
    Minus,
    MousePointer2,
    PanelBottom,
    PanelLeft,
    PanelRight,
    PanelRightOpen,
    Pencil,
    Play,
    PenTool,
    Percent,
    Plus,
    Redo2,
    Rows3,
    Replace,
    Rocket,
    Save,
    ScrollText,
    Search,
    Server,
    Settings,
    Settings2,
    Square,
    SquareArrowOutUpRight,
    SquareDashed,
    SquareTerminal,
    StickyNote,
    SunMoon,
    TabletSmartphone,
    Terminal,
    TextCursorInput,
    TextSearch,
    Trash,
    Type,
    Undo2,
    Users,
    Workflow,
    X,
    Bot,
    type LucideIcon
} from 'lucide-react';

/* What the web client draws in front of a row, so every label starts on the same line. The shell's native menu has none. */
export type MenuIcon = { icon: LucideIcon } | { agent: AgentKind };

const ICONS: Partial<Record<string, LucideIcon>> = {
    file: File,
    edit: Pencil,
    code: CodeXml,
    view: Eye,
    go: Compass,
    run: Rocket,
    window: AppWindow,
    help: CircleHelp,
    'kind-canvas': Frame,
    'kind-drawing': PenTool,
    'kind-diagram': Workflow,
    'kind-chat': MessageSquare,
    'kind-terminal': Terminal,
    'kind-browser': Globe,
    'kind-file': FileText,
    'new-view': Plus,
    'new-agent': Bot,
    'move-to': CornerUpRight,
    layouts: LayoutDashboard,
    'delete-layout': Trash,
    about: Info,
    settings: Settings,
    'project-settings': FolderCog,
    'open-folder': FolderOpen,
    'chat-new': MessageSquarePlus,
    'window-new': AppWindow,
    'window-move': SquareArrowOutUpRight,
    reveal: CornerUpRight,
    'close-cell': X,
    'view-new': Frame,
    'view-new-drawing': PenTool,
    'view-new-diagram': Workflow,
    'view-new-terminal': Terminal,
    'file-new': FilePlus,
    'folder-new': FolderPlus,
    'view-new-file': FileText,
    'view-new-browser': Globe,
    'view-new-separator': Minus,
    'view-new-subheader': Heading,
    'edit-undo': Undo2,
    'edit-redo': Redo2,
    find: TextSearch,
    'find-replace': Replace,
    'find-next': ArrowDown,
    'find-previous': ArrowUp,
    'next-problem': ArrowDown,
    'previous-problem': ArrowUp,
    'code-actions': Lightbulb,
    'rename-symbol': TextCursorInput,
    'go-to-symbol': AtSign,
    'go-to-definition': LocateFixed,
    'go-to-declaration': MapPin,
    'go-to-type-definition': Type,
    'go-to-implementation': Blocks,
    'peek-references': Rows3,
    'peek-definition': FileSearch,
    'quick-info': Info,
    'trigger-completion': ListChecks,
    'parameter-info': Parentheses,
    'history-back': ArrowLeft,
    'history-forward': ArrowRight,
    'recent-locations': History,
    'toggle-line-comment': Slash,
    'toggle-block-comment': Code,
    'join-lines': Merge,
    'split-line': Split,
    'start-new-line': CornerDownLeft,
    'start-new-line-before': CornerLeftUp,
    'toggle-case': CaseSensitive,
    'auto-indent-lines': IndentIncrease,
    'collapse-region': FoldVertical,
    'expand-region': UnfoldVertical,
    'collapse-region-recursively': ListCollapse,
    'expand-region-recursively': ListTree,
    'collapse-all-regions': ChevronsDownUp,
    'expand-all-regions': ChevronsUpDown,
    'fold-selection': FoldHorizontal,
    'select-next-occurrence': ScanSearch,
    'unselect-occurrence': BoxSelect,
    'select-all-occurrences': ListChecks,
    'add-caret-per-selected-line': TextCursor,
    'add-caret-above': ArrowUpToLine,
    'add-caret-below': ArrowDownToLine,
    'toggle-column-mode': Columns3,
    'organize-imports': ListOrdered,
    'format-document': AlignLeft,
    'next-highlight': ArrowDown,
    'previous-highlight': ArrowUp,
    'find-in-files': Search,
    sidebar: PanelLeft,
    'panel-files': Folder,
    'panel-git': GitBranch,
    'panel-devices': TabletSmartphone,
    'panel-toggle': PanelRightOpen,
    'split-right': PanelRight,
    'split-down': PanelBottom,
    'cell-maximize': Expand,
    'node-maximize': Expand,
    'cell-close-others': ListX,
    'cell-close-right': ArrowRightToLine,
    fit: Maximize2,
    'zoom-selection': Focus,
    'zoom-reset': Percent,
    theme: SunMoon,
    fullscreen: Fullscreen,
    'add-terminal': Terminal,
    'add-chat': MessageSquare,
    'add-browser': Globe,
    'add-note': StickyNote,
    'add-text': Type,
    'add-file': FileText,
    'add-group': Group,
    'group-selection': SquareDashed,
    'view-promote': SquareArrowOutUpRight,
    lock: Lock,
    'layout-save': Save,
    'terminal-clear': Eraser,
    'view-fork': GitFork,
    'view-open-in-chat': MessageSquare,
    'view-open-in-terminal': Terminal,
    'view-duplicate': Copy,
    'view-put-on-canvas': Frame,
    'view-reveal': CornerUpRight,
    'view-share': Users,
    'flag-toggle': Flag,
    'view-settings': Settings2,
    'view-delete': Trash,
    'diagram-open-json': Braces,
    palette: Command,
    'view-previous': ChevronsLeft,
    'view-next': ChevronsRight,
    'focus-left': ArrowLeft,
    'focus-right': ArrowRight,
    'focus-up': ArrowUp,
    'focus-down': ArrowDown,
    prompts: Inbox,
    'panel-processes': Activity,
    'panel-problems': CircleAlert,
    usage: Gauge,
    models: ChartSpline,
    'settings-editor': CodeXml,
    'settings-machines': Server,
    'settings-computer': MousePointer2,
    'release-notes': ScrollText,
    onboarding: ListChecks,
    'settings-keyboard': Keyboard,
    'launch-run': Play,
    'launch-stop': Square,
    'launches-stop-all': CircleStop,
    'launches-output': SquareTerminal,
    'launches-edit': Pencil
};

/* Rows that exist once per agent, layout, view or format, by the start of their id. */
const PREFIXES: [prefix: string, icon: LucideIcon][] = [
    ['layout-apply-', LayoutDashboard],
    ['layout-delete-', Trash],
    ['view-move-', ArrowRight],
    ['go-view-', Layers],
    ['launch-choose-', Rocket],
    ['diagram-copy-', Copy],
    ['drawing-copy-', Copy],
    ['diagram-save-', Download],
    ['drawing-save-', Download],
    ['diagram-show-', Frame],
    ['drawing-show-', Frame]
];

const AGENT_ROW = /^agent-(?:view-)?(?:chat|terminal)-(.+)$/;

export function menuIconOf(id: string): MenuIcon | null {
    const agent = AGENT_ROW.exec(id)?.[1];
    if (agent !== undefined) {
        return { agent: agent as AgentKind };
    }
    const icon = ICONS[id] ?? PREFIXES.find(([prefix]) => id.startsWith(prefix))?.[1];
    return icon === undefined ? null : { icon };
}
