import { AgentKindSchema, type ContextSource } from '@ruimte/contracts';
import { MAX_AGENT_DEPTH, MAX_TEAM_DEPTH } from '../canvas/depth.ts';
import { NODE_VERB_KINDS } from '../canvas/node-kinds.ts';

/* Asked for a CLI by name, a model that has not read the names goes looking through its own tools
   for one and reports back that this machine has none, so the verb names them where it is offered. */
const CLI_NAMES = AgentKindSchema.options.join(', ');

/* Told only that it places "nodes", a model asked for a note writes a file with its own tools and
   the canvas stays empty, so the kinds `node new` opens are named where the command is introduced. */
const NODE_KINDS = NODE_VERB_KINDS.join(', ');

/* The brake below reads as "use your own means" exactly when the person asked for a second agent
   beside this one, so the difference between answering yourself and hiding the work is spelled out. */
const NOT_A_SUBAGENT = 'An agent the person asks for is one of these, never a subagent of your own.';

/*
 * What the verb opens, with the reason not to reach for it: a model that reads only what it can do
 * opens a team for work it could have answered itself, and every agent leaves a node behind.
 */
const opensAt = (depth: number): string | null => {
    if (depth < MAX_TEAM_DEPTH) {
        return `It also opens agents (\`agent <cli>\` for one, \`team\` for several in parallel, with <cli> one of ${CLI_NAMES}), which is for work the person asked you to split or that truly runs in parallel: every agent is a node on their canvas until someone removes it, so answer yourself whatever you can. ${NOT_A_SUBAGENT}`;
    }
    if (depth < MAX_AGENT_DEPTH) {
        return `It also opens a helper agent with \`agent <cli>\`, with <cli> one of ${CLI_NAMES}, which is for work the person asked you to split: that agent is a node on their canvas until someone removes it, so answer yourself whatever you can. ${NOT_A_SUBAGENT}`;
    }
    return null;
};

/* Said only while a person turned computer use on for this machine; off, the noun only refuses. */
const COMPUTER_NOTE =
    'With `ruimte-context computer` you read and operate the apps of this Mac, each only once the person lets you into it; use it only when they ask you to work in an app.';

// Generated by the daemon so every CLI and SSH host receives current verbs and depth limits.
export const verbsNote = ({ depth, standalone = false, computer = false }: { depth: number; standalone?: boolean; computer?: boolean }): string => {
    /* Told what it is not ("not a node on a canvas"), a chat of its own reasons from the canvas in every
       answer, so this says what it can do and names the canvas only as a place to open something. */
    if (standalone) {
        return [
            "Ruimte: `ruimte-context` is a command you run in your shell, not a tool. It reads the context linked to this chat and manages the project's views; `ruimte-context help` lists its verbs and nouns.",
            "Delegate work within this chat with your CLI's own subagents, and keep any model the person asked for.",
            'Only when the person asks for an agent, note or drawing in Ruimte itself, open it with `ruimte-context` and name where it goes with --view.',
            ...(computer ? [COMPUTER_NOTE] : []),
            'Ids in its output are for your commands; to the person, name things by their title, never by id.'
        ].join(' ');
    }
    const parts = [
        // A model with a tool search otherwise goes looking for a tool of that name and gives up.
        `Ruimte: \`ruimte-context\` is a command you run in your shell, not a tool. It reads context linked to you and opens nodes on the person's canvas (\`node new\`): ${NODE_KINDS}. A note or drawing they ask for is one of those, not a file you write.`,
        '`ruimte-context help` lists the verbs and nouns, and `ruimte-context help <verb or noun>` details one.'
    ];
    const opens = opensAt(depth);
    if (opens !== null) {
        parts.push(opens);
    }
    if (depth < MAX_AGENT_DEPTH) {
        parts.push('With `--task` a result comes back as your next message once it settles, so end your turn instead of polling.');
    }
    if (computer) {
        parts.push(COMPUTER_NOTE);
    }
    parts.push('Ids in its output are for your commands; to the person, name things by their title, never by id.');
    return parts.join(' ');
};

// Past this many, a busy canvas would flood a prompt line; the rest becomes a count.
const MAX_NAMED = 5;

export const CONTEXT_LEAD = 'Ruimte: linked context is available with ruimte-context (list, read <id>): ';

const quote = (source: ContextSource): string => `"${source.title}" (${source.kind})`;

const nameSources = (sources: ContextSource[]): string => {
    const named = sources.slice(0, MAX_NAMED).map(quote);
    const rest = sources.length - named.length;
    return rest > 0 ? `${named.join(', ')} and ${rest} more` : named.join(', ');
};

/*
 * One line that tells an agent the linked context exists and how to read it. Shown above a
 * shell's first prompt and returned to the agent CLIs' prompt hooks, where the agent has no
 * system prompt of ours. Null without links, so a plain shell stays quiet.
 */
export const contextHint = (sources: ContextSource[]): string | null => {
    if (sources.length === 0) {
        return null;
    }
    return `${CONTEXT_LEAD}${nameSources(sources)}.`;
};

/*
 * The same line for a chat, with the reason to trust it: a model that hears only that context exists
 * answers a question about "the device" from whatever its own tools happen to name, and sounds sure of it.
 */
export const contextPrompt = (sources: ContextSource[]): string | null => {
    const hint = contextHint(sources);
    if (hint === null) {
        return null;
    }
    return `${hint} This is what the person means, so prefer it over anything your own tools or servers turn up.`;
};

/*
 * What an agent is told once at the start of a chat process, so it knows the CLI without being
 * nagged every turn. Claude Code takes it as a system prompt and Codex as a thread's developer instructions.
 */
export const chatPrompt = ({
    sources,
    depth,
    standalone,
    computer
}: {
    sources: ContextSource[];
    depth: number;
    standalone?: boolean;
    computer?: boolean;
}): string => {
    const note = verbsNote({ depth, standalone, computer });
    const prompt = contextPrompt(sources);
    return prompt === null ? note : `${note} ${prompt}`;
};

/*
 * Session start receives the CLI note and full link list. Later hooks carry only link changes and
 * queued messages, avoiding repeated instructions on every prompt.
 */
export const hookContext = (
    event: string,
    sources: ContextSource[],
    turn: { changed?: string | null; messages?: readonly string[]; depth?: number; verbs?: boolean; computer?: boolean } = {}
): string | null => {
    const start = event === 'SessionStart';
    const hint = contextHint(sources);
    const parts = [
        ...(start && turn.verbs !== false ? [verbsNote({ depth: turn.depth ?? 0, computer: turn.computer === true })] : []),
        ...(hint === null ? [] : [hint]),
        ...(start || !turn.changed ? [] : [turn.changed]),
        ...(turn.messages ?? [])
    ];
    return parts.length === 0 ? null : parts.join(' ');
};

/*
 * What an agent that already knows the CLI must hear at the start of its next turn: which
 * links came and went since the previous one. Null when the set is the same, so a chat is
 * never nagged. Sources are matched by id; a renamed one is not a change.
 */
export const contextChangeNote = (previous: ContextSource[], current: ContextSource[]): string | null => {
    const before = new Set(previous.map((source) => source.id));
    const after = new Set(current.map((source) => source.id));
    const added = current.filter((source) => !before.has(source.id));
    const removed = previous.filter((source) => !after.has(source.id));
    if (added.length === 0 && removed.length === 0) {
        return null;
    }
    const parts = ['Ruimte: the linked context changed since your last turn.'];
    if (added.length > 0) {
        parts.push(`Added: ${nameSources(added)}.`);
    }
    if (removed.length > 0) {
        parts.push(`Removed: ${nameSources(removed)}.`);
    }
    parts.push(current.length === 0 ? 'Nothing is linked now.' : 'Run `ruimte-context` to list it and `ruimte-context read <id>` to read one item.');
    return parts.join(' ');
};
