export { AGENT_COLORS } from './attribution.ts';
export { createSmartEditorEngine } from './engine.ts';
export { DEFAULT_SMART_KEYS } from './smart-keys.ts';
export { shikiScopeColors, shikiTokenizers } from './shiki.ts';
export type {
    Editor,
    EditorAttributionHover,
    EditorAttributionMark,
    EditorMarkColor,
    EditorBlock,
    EditorChangeKind,
    EditorChangeMark,
    EditorCodeVision,
    EditorCodeVisionEntry,
    EditorClick,
    EditorCodeBlockOptions,
    EditorClickHandler,
    EditorCommand,
    EditorContextMenu,
    EditorEngine,
    EditorFindQuery,
    EditorFoldHints,
    EditorFoldOutline,
    EditorFoldRange,
    EditorFoldSymbol,
    EditorFolds,
    EditorFindState,
    EditorReplaceOptions,
    EditorGutterAction,
    EditorGutterMarker,
    EditorIndentation,
    EditorContentChange,
    EditorHighlight,
    EditorHighlightKind,
    EditorHover,
    EditorInlayHint,
    EditorKeyHandler,
    EditorLineAction,
    EditorLineHighlight,
    EditorMarker,
    EditorMessages,
    EditorMarkerSeverity,
    EditorReveal,
    EditorRect,
    EditorSmartKeys,
    EditorOptions,
    EditorPosition,
    EditorRemoteCursor,
    EditorRange,
    EditorTextChange,
    EditorTrackedRange,
    EditorRunCommand,
    EditorSelectionRanges,
    EditorTheme,
    EditorViewCommand,
    EditorWidget,
    FoldRole,
    KeyChord,
    LineToken,
    ScopeColorSource,
    ScopeColors,
    ScopeStyle,
    EditorSemanticToken,
    LineTokenizer,
    SmartEditorEngineOptions,
    TokenizedLine,
    TokenizerSource
} from './types.ts';
