[package]
name = "php-analysis"
description = "Syntax-tree and index queries for the PHP language server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
php-index = { version = "0.1.0", path = "../index" }
php-syntax = { version = "0.1.0", path = "../syntax" }

[dev-dependencies]
expect-test = "1.5.1"
criterion = "0.7.0"

[[bench]]
name = "completion"
harness = false
